trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs: 
- deployment: VMDeploy
  displayName: web
  environment:
    name: themeleaf-test
    resourceType: VirtualMachine
  strategy:
    rolling:
      maxParallel: 1 
      deploy:
        steps:
        - task: Bash@3 
          inputs:
            targetType: 'inline'
            script: |
                sudo apt-get update -y 
                sudo apt install openjdk-8-jdk -y
                cd /home/admin123/
                git clone "https://sanket0802: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@github.com/sanket0802/themeleaf.git"
                cd /home/admin123/themeleaf/thymeleafExample/
                sudo apt-get install maven -y 
                mvn test
                mvn package
                mvn install
                cd /home/admin123/themeleaf/thymeleafExample/target
                java-jar work-0.0.1-SNAPSHOT.jar 
                
