version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/p2g3u3g4

  build:
    commands:     
      - echo "Building Maven project..."
      - cd thymeleafExample
      - mvn clean install -DskipTests=true
      - echo "Building Docker image...."
      - docker build -t public.ecr.aws/p2g3u3g4/thm-codeb-repo:latest -f Dockerfile .
      - echo "Docker image built"

  post_build:
    commands:
      - echo "Tagging Docker image..."
      - docker tag public.ecr.aws/p2g3u3g4/thm-codeb-repo:latest public.ecr.aws/p2g3u3g4/thm-codeb-repo:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo "Pushing Docker image to ECR..."
      - docker push public.ecr.aws/p2g3u3g4/thm-codeb-repo:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo "Docker image pushed to ECR"
      - echo "Writing image definitions file..."
      - printf '[{"name":"demo-apps2","imageUri":"%s"}]' public.ecr.aws/p2g3u3g4/thm-codeb-repo:$CODEBUILD_RESOLVED_SOURCE_VERSION > imagedefinitions.json

artifacts:
  files: imagedefinitions.json

cache:
  paths:
    - ~/.m2/repository




#=====================================================================================================================================================================
# version: 0.2

# phases:
#   install:
#     runtime-versions:
#       java: corretto11
#   pre_build:
#     commands:
#       - echo Logging in to Amazon ECR...
#       - aws --version
#       - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
#       - REPOSITORY_NAME=my-docker-repo  # Replace with your desired ECR repository name
#       - REPOSITORY_URI=$(aws ecr describe-repositories --repository-names $REPOSITORY_NAME --query "repositories[0].repositoryUri" --output text)
#       - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
#       - IMAGE_URI=$REPOSITORY_URI:$IMAGE_TAG
#   build:
#     commands:
#       - echo Build started on `date`
#       - echo Building the Docker image...
#       - docker build -t $IMAGE_URI -f Dockerfile .  # Reference the Dockerfile
#   post_build:
#     commands:
#       - echo Build completed on `date`
#       - echo Pushing the Docker image to ECR...
#       - docker push $IMAGE_URI
# artifacts:
#   files: '**/*'
