name: Build and Test Spring Boot App

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '11'

    - name: Build with Maven
      run: |
        mvn clean package -DskipTests

    - name: Run tests
      run: |
        mvn test

    - name: Run the application
      run: |
        java -jar target/work-0.0.1-SNAPSHOT.jar &
        sleep 10 # Give the app some time to start
        curl http://localhost:8086 # Replace with your app's URL
        
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          # Stop any existing instance
          pkill -f your-app.jar
          # Copy the new jar file
          scp /github/workspace/target/your-app.jar ubuntu@${EC2_HOST}:/home/ubuntu/
          # Run the new instance
          ssh ubuntu@${EC2_HOST} "nohup java -jar /home/ubuntu/your-app.jar &"
