name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # Increase the timeout to 60 minutes
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '8'

    - name: Build with Maven
      run: |
        cd thymeleafExample
        mvn clean install

    - name: Deploy and Run on EC2
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_KEY }}
        SOURCE: "./thymeleafExample/target"
        REMOTE_HOST: "54.175.41.89"
        REMOTE_USER: "ubuntu"
        TARGET: "/home/ubuntu/"
        script: |
          # Stop any existing instance
          pkill -f work-0.0.1-SNAPSHOT.jar
          # Run the new instance
          nohup java -jar work-0.0.1-SNAPSHOT.jar &
          - name: Execute Jar File
          #While executing Jar file, kill port 80 if anything is running on it 
          run: sudo kill -9 `sudo lsof -t -i:80` & sudo java -jar /home/ubuntu/actions-runner/target/work-0.0.1-SNAPSHOT.jar &
