# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

#trigger when anything is pushed to the main branch
on:
  push:
    branches: [ "main" ]

jobs:
  build:

    #build will run on a self-hosted server
    runs-on: self-hosted

    steps:
    #check out repository and clone repository to the self-hosted server
    - uses: actions/checkout@v3
    
    #set up Java on the server
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        cd thymeleafExample
        mvn clean install
    - name: Execute Jar File
    #While executing Jar file, kill port 8086 if anything is running on it 
      run: |
        sudo kill -9 `sudo lsof -t -i:8086` & sudo java -jar /home/ubuntu/actions-runner/_work/themeleaf/themeleaf/thymeleafExample/target/work-0.0.1-SNAPSHOT.jar &
